spring:
  application:
    name: configuration-service
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
#        git:
#          uri: https://github
#  .com/lmyanicelli/configuration-repository-parcial.git
#          default-label: main

server:
  port: 8888
