spring:
  application:
    name: catalog-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: catalogdb

server:
  port: 8071

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true

  zipkin:
    baseUrl: http://localhost:9411/
    enabled: true
    sender:
      type: rabbit

  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672

queue:
  movie:
    name: MovieQueue

queueSerie:
  serie:
    name: SerieQueue
