spring:
  application:
    name: serie-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: seriedb

server:
  port: 8062

eureka:
  client:
    fetchRegistry: false
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true

  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672

queueSerie:
  serie:
    name: SerieQueue